name: "Personal Tuya Devices - Custom Dimmer"
packageKey: "br.com.wesley.beta.tuya-devices-custom"
description: "This driver is intended to work with devices that use 0xEF00 Tuya Cluster (Max Brightness 95% Limit)"
vendorSupportInformation: "Personal Tuya Devices Custom"
permissions:
  zigbee: {}